version: "3.1"

services:

  logstash:
    image: logstash:6.7.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    links:
     - elasticsearch
    depends_on:
     - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600" 
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
     - elk

  elasticsearch:
    image: elasticsearch:6.7.1
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - "./es_data/es_data:/usr/share/elasticsearch/data/"
     - "./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms512m"
      ELASTIC_PASSWORD: "password"
      
    networks:
     - elk

  kibana:
    image: kibana:6.7.1
    ports:
     - "5601:5601"
    links:
     - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
     - elasticsearch
    networks:
     - elk
 
networks:

  elk:
    driver: bridge