version: "3.1"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: "kafka-broker1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper  
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.1.214"
      KAFKA_CREATE_TOPICS: "jenkins-log:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_BROKER_ID: "1"   